// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  REPO_ORG: string;
  REPO_NAME: string;
  REPO_PAT: string;
  GITHUB_APP_ID: string;
  GITHUB_CLIENT_ID: string;
  GITHUB_CLIENT_SECRET: string;
  GITHUB_PRIVATE_KEY: string;
  SENTRY_DSN: string;
  SENTRY_ENVIRONMENT: string;
}
