// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	REPO_ORG: string;
	REPO_NAME: string;
	REPO_PAT: string;
	SENTRY_DSN: string;
}
