name: 'Deployment staging'

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    name: 'Deploy workers'
    environment: 'staging'
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: 'Deploy'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: '${{ secrets.CLOUDFLARE_API_TOKEN }}'
          command: 'deploy --name ${{ secrets.CLOUDFLARE_WORKER_NAME }}'

